### ISSUE TITLE
Support for mobile devices

### ISSUE THREAD

**Issue by ooduor** [w3shaman/jquery-coolautosuggest#2]
It does not work well on smart phones. When the drop down list show and you select your choice. The input field is not populated with the choice yet the dropdown disappears. Also if you have a hidden field with ID, it will not get populated.

**Comment by w3shaman** [comment]
Yes there is such trouble and I'm still working to fix that. If you have any idea please let me know.

**Comment by w3shaman** [comment]
Thanks for your contribution. The problem is solved in version 2.3.2,
